### ISSUE TITLE
Storing password on flat config file seem to be risky

### ISSUE THREAD

**Issue by hegdeashwin** [devdil/switchy#12]
**What is happening?**

- Currently, by default Switchy stores user inputed username and password in non-encrypt form on a generated file `switchy.conf`. This seems to be a security issue, if the system is vulnerable in that case this file could leak critical data.

**What is expected?**

- Critical data must not be directly available or in readable form to avoid any potential data leak.

**Possible Solutions**

Naive thoughts on possible solutions to explore more

1. We could use some encryption to encrypt and decrypt the critical data before storing/retrieving the data on/from disk. May be user could provide the Salt key to encrypt/decrypt the data and this Salt could be store in memory.
2. Avoid storing critical data on disk instead store it in memory in along with point (1).
3. Use either built-in or 3rd party features like Keychain Access (on MacOS) to store the critical data. I believe this approach is being used with in Git system to store the passphrase.

**Comment by hegdeashwin** [comment]
@devdil I believe we can now release new version as its a major change. Shall I go ahead and publish the new version along with release content?

**Comment by devdil** [comment]
Yes
